version: "3"
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
  postgres-master:
    image: postgres:15
    container_name: postgres-master
    environment:
      - POSTGRES_PASSWORD=Niks123
      - POSTGRES_DB=outline
    volumes:
      - ./data/master:/var/lib/postgresql/data
      - ./postgre-config/primary/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgre-config/primary/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    restart: always
    command: postgres -c wal_level=logical
  postgres-slave:
    image: postgres:15
    container_name: postgres-slave
    environment:
      - POSTGRES_PASSWORD=Niks123
      - POSTGRES_DB=outline
      - POSTGRES_MASTER_HOST=postgres-master
    volumes:
      - ./data/slave:/var/lib/postgresql/data
      - ./postgre-config/replica/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgre-config/replica/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5433:5432"
    depends_on:
      - postgres-master
    restart: always
    command: postgres -c wal_level=logical
  s3:
    image: lphoward/fake-s3
    ports:
      - "127.0.0.1:4569:4569"
    volumes:
      - ./fakes3:/fakes3_root
